send_command:
  target:
    device:
      integration: necprojector
  fields:
    command:
      required: true
      example: "00850000010187"
      selector:
        text:
send_ascii_command:
  target:
    device:
      integration: necprojector
  fields:
    command:
      required: true
      example: "power on"
      selector:
        text: